use crate::e2es;

e2es! {
    array,
    candidate_not_viable,
    constraints,
    constraints_in_constructor,
    deref_member_ref,
    destructor,
    generics,
    import_all,
    integer,
    integer_not_eq_rational,
    memory,
    missing_fields,
    monomorphize,
    monomorphize_predeclared,
    multiple_errors,
    multiple_initialization,
    non_class_constructor,
    plus_assign,
    predeclare_function,
    predeclare_vars,
    rational,
    reference_mut,
    references,
    specify_variable_ty,
    string,
    traits,
    type_as_value,
    wrong_initializer_type
}
