use crate::e2e;

e2e!(array);
e2e!(candidate_not_viable);
e2e!(constraints);
e2e!(constraints_in_constructor);
e2e!(deref_member_ref);
e2e!(generics);
e2e!(integer_not_eq_rational);
e2e!(missing_fields);
e2e!(monomorphize);
e2e!(multiple_errors);
e2e!(multiple_initialization);
e2e!(non_class_constructor);
e2e!(predeclare_function);
e2e!(predeclare_vars);
e2e!(reference_mut);
e2e!(references);
e2e!(traits);
e2e!(type_as_value);
e2e!(wrong_initializer_type);
